### ISSUE TITLE
Using Struct inside a script removes the parameter input field

### ISSUE THREAD

**Issue by alxflw** [onflow/flow-playground#204]
**Describe the bug**
If a `struct` is added to a script that has arguments, the input field in the execution modal disappears.

**To Reproduce**

https://user-images.githubusercontent.com/97620081/150460313-c8d29ec1-5c7f-4cb9-8e8f-a0208bb54e7e.mov

**Expected behavior**
The input field for the argument(s) is shown.

**Comment by MaxStalker** [comment]
There was a "bug" with language server (which probably still exist on Playground, since it's implemented via npm package), which would think this is invalid script and return you empty array of arguments.

Should probably be resolved by new release of package from here - https://github.com/onflow/cadence/tree/master/npm-packages/cadence-language-server - and then reimporting new version on Playground.

@turbolent can you tell me what is the process to releasing new version of language server package?

**Comment by MaxStalker** [comment]
More investigation :)
This was fixed here - https://github.com/onflow/cadence/pull/1175
So we need to update Cadence version in Language server and npm package.

**Comment by turbolent** [comment]
> This was fixed here - https://github.com/onflow/cadence/pull/1175

Correct, this should be fixed.

The language server is currently updated to v0.20.2: https://github.com/onflow/cadence/blob/master/languageserver/go.mod#L9, which should hopefully include this fix.

I'll tag and publish the language server

**Comment by turbolent** [comment]
I fixed the NPM package and published v0.20.2 of it at https://www.npmjs.com/package/@onflow/cadence-language-server

**Comment by MaxStalker** [comment]
Fixed in #222 
Should be available in next Playground deployment.

@turbolent thank you for your help :bow:
