### ISSUE TITLE
Hello World example fails because of Language Server 

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-playground#212]
**Describe the bug**

https://play.onflow.org/f51905e8-6030-4641-9324-11a3f1a6091c

Language Server has problem with signers I guess. Playground doesn't show signers panel on Say Hello Transaction. 

When you remove comments it works.

**Comment by ObjectPlayer** [comment]
Hi @bluesign actually there is an issue with playground, actually if you see your `Say Hello Transaction` than you can noticed that you have added `prepare` in the comments which doesn't have any authAccount, that's why you are not seeing signing panel in the `Say Hello Transaction`. In summary playground also reading your comments too  

```
// Transaction1.cdc

import HelloWorld from 0x01

// Transactions are declared with the "transaction" keyword.
//
// They have three possible stages:
//
// prepare(acct:AuthAccount): This block has full access to the accounts that signed
// the transaction. This is where resources should be stored, removed,
// or used to create references.
//
// execute: This is the main part of the transaction and is
// the stage where function calls and calls to external
// contracts and resources should occur.
//
// post: This block contains optional postcondition checks that can be used to
// verify that the transaction was executed correctly.

transaction {

    // No need to do anything in prepare because we are not working with
    // account storage.
	prepare(acct: AuthAccount) {}

    // In execute, we simply call the hello function
    // of the HelloWorld contract and log the returned String.
	execute {
	  	log(HelloWorld.hello())
	}
}
```
From above transaction, playground also reading comments which have **prepare** keyword

>     // Transactions are declared with the "transaction" keyword.
>     //
>     // They have three possible stages:
>     //
>     // prepare: This block has full access to the accounts that signed
>     // the transaction. This is where resources should be stored, removed,
>     // or used to create references.
>     //
>      // execute: This is the main part of the transaction and is
>      // the stage where function calls and calls to external
>      // contracts and resources should occur.
>      //
>      // post: This block contains optional postcondition checks that can be used to
>      // verify that the transaction was executed correctly.

>     // No need to do anything in prepare because we are not working with
>     // account storage.

If you just remove **prepare** from comment you can see the signing panel, also if you just add bellow line the comment still you can see the signing panel e.g:

>     // prepare(acct:AuthAccount): This block has full access to the accounts that signed

**Comment by KhaledAylii** [comment]
Experiencing this too, comments are being parsed for the "prepare" keyword
