### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by devbugging** [onflow/flow-playground#324]
We need to update all dependencies, especially critical ones like the Monaco editor. They need to be up to date so we will be able to maintain the codebase in the future and include any bugfixes that were done.

- [x] Upgrade base dependencies (#336)
- [x] Upgrade monaco-languageclient
- [ ] Upgrade to Apollo 3 with mutation hooks
- [ ] Upgrade to React 18. This caused a linter regression, see #336 . Try again after fixing rules-of-hooks violations

**Comment by alse** [comment]
Status update:

- #336  upgrades all dependencies except those related to Apollo and monaco-languageclient + vscode-jsonrpc
- Upgrading monaco-languageclient and switching to vscode-ws-jsonrpc is a larger task we can break out
- Upgrading to Apollo 3 is also a larger task that will require some refactoring and using hooks instead of the projectMutator
- React was only upgraded to 17. React 18 caused a linting regression:
    1. Open a new project
    2. Deploy a HelloWorld contract
    3. Click on the Transaction template
    4. The HelloWorld contract is not found on 0x01 until a page reload

**Comment by MrDSGC** [comment]
- Playground monaco editor is currently on v0.33 whereas most current is v0.34. no updates needed for the time being
- Apollo 3 upgrade will still require projectMutator class to be refactored https://github.com/onflow/flow-playground/issues/283
