### ISSUE TITLE
Deploy Playground production

### ISSUE THREAD

**Issue by devbugging** [onflow/flow-playground#341]

**Comment by MrDSGC** [comment]
- Created loose testing plan for playground frontend: https://docs.google.com/document/d/1pwzyEebCbA-EfGmo3nL_ToGz2Wu8Y8maMuJh6cUeJxU/edit?usp=sharing if there are any specific flows missing then add them to the doc please
- Setup Cypress dashboard for playground
- Investigating using this public library to workaround cypress not selecting react components : https://www.npmjs.com/package/cypress-react-selector let me know if there are any concerns here because i think im going to followthrough

**Comment by devbugging** [comment]
@MrDSGC I believe this comment should be somewhere else? :D

**Comment by devbugging** [comment]
This task was significantly delayed, leaving me and @DylanTinianov with less time in the sprint for other tasks.
