### ISSUE TITLE
Language Server out of sync with backend API

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground#556]
**Describe the bug**
Language Server out of sync with Playground Backend API.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy ContractA to 0x01
2. Deploy ContractB (which imports ContractA) to 0x02
3. Create ContractC which imports ContractB from 0x02, the LS fails to check import

**Expected behavior**
ContractC should be able to import ContractB

**Screenshots**
<img width="1512" alt="Screen Shot 2023-02-06 at 2 58 39 PM" src="https://user-images.githubusercontent.com/19377621/217072299-100feab6-c606-4c2a-bd64-a13793162b3c.png">

**Comment by bluesign** [comment]
s/out of sync/not connected/

Missing piece: https://github.com/onflow/flow-playground/blob/c3205b68430d0310d68aa4f49357a433e08aa67c/src/hooks/useLanguageServer.ts#L73

**Comment by bthaile** [comment]
`getCode` is not able to get the code given the `_address`. Example, _address is '0000000000000001.HelloWorld' This gives account and deployed contract name. 
The UI has two data structures 
1. deployedContracts which is a list of contract names that have been deployed. 
2. contract code files, they have filename and contract code
So in the UI the contract code can not easily be matched up with the import. Since the user can change the contract file but the deployed contract is unchanged. 

In order to get the deployed contract code the UI needs to call playground-api to get the contract that has been deployed in order to pass to language server to get correct error messaging. 

Current suggestion is to add contract `name` to ContractDeployment would solve this issue.

```
type ContractDeployment {
  id: UUID!
  script: String!
  address: Address!
  errors: [ProgramError!]
  events: [Event!]
  logs: [String!]
}
```
