### ISSUE TITLE
Sharing doesn't work

### ISSUE THREAD

**Issue by shaununderwood** [onflow/flow-playground#635]
**Describe the bug**
Sharing doesn't work.
Navigating to the shared link takes one to https://play.flow.com/local-project

**To Reproduce**
On a new project, update a comments. save. copy share link into another browser, or same browser new tab.
An example link: https://play.flow.com/1e783744-182d-404c-a3fc-8962180c371e?type=contract&id=170b8124-b688-41cc-af0d-44ccc44dbb3f

**Expected behavior**
At least to see the project that was displaying at the time of copying the hsare link

**Screenshots**
No need

**Desktop (please complete the following information):**
iOS, windows, any browser

**Comment by bthaile** [comment]
@DylanTinianov 
Seeing error from api when trying to query for that project. 
![2023-04-06 12 29 14](https://user-images.githubusercontent.com/3970376/230452839-a68d30f2-f023-4755-9522-39c0f94a4801.gif)

**Comment by DylanTinianov** [comment]
This issue is being caused due to the state recreation failing. When re-running certain transaction executions, Cadence runtime errors are occurring. This causes the project to not be loaded. I have created another issue for this on the backend (https://github.com/onflow/flow-playground-api/issues/249)  and will close this one.
