### ISSUE TITLE
Cannot deploy NFL AllDay smart contract

### ISSUE THREAD

**Issue by EricLin-wk** [onflow/flow-playground#642]
**Describe the bug**
Cannot deploy NFL AllDay smart contract to the playground. No syntax errors were found, but getting "Oops! Something went wrong. If you'd like, please report the Bug. Thank you!" when trying to deploy. No additional detail is surfaced to explain what went wrong.

**To Reproduce**
Deploy smart contracts: NonFungibleToken, FungibleToken, MetadataViews
Deploy the main smart contract: https://flow-view-source.com/mainnet/account/0xe4cf4bdc1751c65d/contract/AllDay

**Expected behavior**
AllDay smart contract deploy should be successful

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.3
 - Browser Chrome
 - Version 111.0.5563.146 (Official Build) (arm64)

**Additional context**

**Comment by bthaile** [comment]
Thanks, we are having some intermittent backend issues. I'll add this issue to the playground-api list. 
Current playground api epic
https://github.com/onflow/flow-playground-api/issues/243

**Comment by DylanTinianov** [comment]
This seems to work for me.

Did you change the addresses of NonFungibleToken, and FungibleToken to Playground addresses and import them in MetadataViews similar to the following? @EricLin-wk 
![Image](https://user-images.githubusercontent.com/19377621/231814592-b7808b81-eed8-4f3f-b2d4-ab02bb35188a.png)

I then deployed NonFungibleToken to 0x01, FungibleToken to 0x01, and then MetadataViews to 0x01. I am then able to deploy the AllDay contract to any account without issues. You may also want to confirm where you got the standard contracts from and make sure they are the correct ones.

![Image](https://user-images.githubusercontent.com/19377621/231814216-7d5cc47a-6814-4657-96df-f81e78b5019e.png)

Please try again, and let me know if you are still seeing this issue. There were some other issues that have since been resolved which may have been interfering with your deployments. Sorry for the inconvenience!

**Comment by EricLin-wk** [comment]
Confirmed it's working now, likely just a temporary issue. Thanks!
